-d D:\Documentos\REPOS\Github\Tang-Nano\tutorials\Obijuan_open_FPGA\T05-prescaler\impl\gwsynthesis\T05-prescaler.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst D:\Documentos\REPOS\Github\Tang-Nano\tutorials\Obijuan_open_FPGA\T05-prescaler\src\T05-prescaler.cst
-cfg D:\Documentos\REPOS\Github\Tang-Nano\tutorials\Obijuan_open_FPGA\T05-prescaler\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
