-d D:\Documentos\REPOS\Github\Tang-Nano\tutorials\Obijuan_open_FPGA\T02-Fport\impl\gwsynthesis\T02-Fport.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst D:\Documentos\REPOS\Github\Tang-Nano\tutorials\Obijuan_open_FPGA\T02-Fport\src\T02-Fport.cst
-cfg D:\Documentos\REPOS\Github\Tang-Nano\tutorials\Obijuan_open_FPGA\T02-Fport\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
