-d D:\Documentos\REPOS\Github\Tang-Nano\tutorials\Obijuan_open_FPGA\T04-counter\impl\gwsynthesis\T04-counter.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst D:\Documentos\REPOS\Github\Tang-Nano\tutorials\Obijuan_open_FPGA\T04-counter\src\T04-counter.cst
-cfg D:\Documentos\REPOS\Github\Tang-Nano\tutorials\Obijuan_open_FPGA\T04-counter\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
