-d D:\Documentos\REPOS\Github\Tang-Nano\tutorials\Obijuan_open_FPGA\T01-setbit\impl\gwsynthesis\T01-setbit.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst D:\Documentos\REPOS\Github\Tang-Nano\tutorials\Obijuan_open_FPGA\T01-setbit\src\T01-setbit.cst
-cfg D:\Documentos\REPOS\Github\Tang-Nano\tutorials\Obijuan_open_FPGA\T01-setbit\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
